/** Wrappers around native developer tools (tsc, eslint, etc.) used by quality handlers. */
export const NATIVE_TOOL_NAMES = [
  "vibeguide_heuristic_bug",
  "vibeguide_trace_journey",
  "vibeguide_impact",
  "vibeguide_test_plan",
  "vibeguide_snapshot",
  "vibeguide_deploy_check",
  "vibeguide_suggest_fix",
  "vibeguide_changelog",
  "vibeguide_dependency_graph",
  "vibeguide_diff_summary",
  "vibeguide_what_changed",
  "vibeguide_regression",
  "vibeguide_scan_repo",
  "vibeguide_get_file",
  "vibeguide_get_deps",
  "vibeguide_type_check",
  "vibeguide_test_coverage",
  "vibeguide_circular_deps",
  "vibeguide_dead_code",
  "vibeguide_complexity",
  "vibeguide_a11y_check",
  "vibeguide_secret_scan",
  "vibeguide_i18n_gap",
  "vibeguide_doc_gap",
  "vibeguide_perf_budget",
  "vibeguide_monorepo_route",
  "vibeguide_review_pr",
  "vibeguide_founder_brief",
  "vibeguide_meeting_notes",
] as const;
