/** Dictionary keyword tiếng Việt + Anh cho smart_route — map plugin/tool → searchable keywords. */
export const PLUGIN_KEYWORDS: Record<string, string[]> = {
  "chrome-devtools-mcp": [
    "chậm",
    "load lâu",
    "ui chậm",
    "performance",
    "web vitals",
    "lighthouse",
    "audit",
    "fps",
    "render",
    "chrome",
    "devtools",
    "mạng",
    "network",
    "memory leak",
    "screenshot",
    "screenshot full page",
    "console",
    "lcp",
    "cls",
    "inp",
    "core web vitals",
    "tối ưu",
    "optimize",
  ],
  "gitnexus": [
    "codebase",
    "repo",
    "architecture",
    "refactor",
    "tìm file",
    "impact",
    "dependency",
    "code graph",
    "knowledge graph",
    "cypher",
    "query",
    "tác động",
    "đổi tên",
    "rename",
    "cross-repo",
    "module",
  ],
  "stripe": [
    "thanh toán",
    "payment",
    "checkout",
    "thẻ",
    "billing",
    "subscription",
    "invoice",
    "charge",
    "refund",
    "stripe",
    "giá",
    "pricing",
  ],
  "supabase": [
    "database",
    "sql",
    "postgres",
    "auth",
    "realtime",
    "lưu trữ",
    "bảng",
    "table",
    "row level security",
    "rls",
    "function",
    "edge",
    "storage",
    "bucket",
    "supabase",
  ],
  "huggingface-skills": [
    "ml",
    "model",
    "train",
    "dataset",
    "inference",
    "embedding",
    "fine-tune",
    "hugging face",
    "transformers",
    "gradio",
    "vision",
    "nlp",
    "ai model",
    "thử nghiệm model",
  ],
  "code-review": [
    "review",
    "pr",
    "pull request",
    "merge",
    "code review",
    "đánh giá code",
    "duyệt",
    "approve",
    "reject",
  ],
  "feature-dev": [
    "feature",
    "tính năng",
    "implement",
    "development",
    "phát triển",
    "build feature",
    "thiết kế feature",
    "plan",
    "blueprint",
  ],
  "superpowers": [
    "plan",
    "debug",
    "test",
    "tdd",
    "skill",
    "superpowers",
    "lập kế hoạch",
    "ghi nhớ",
    "agent skill",
    "workflow",
  ],
  "frontend-design": [
    "ui",
    "ux",
    "design",
    "giao diện",
    "layout",
    "css",
    "responsive",
    "component",
    "theme",
    "dark mode",
    "color",
    "typography",
    "spacing",
    "frontend",
    "figma",
  ],
  "security-guidance": [
    "security",
    "xss",
    "injection",
    "auth",
    "bảo mật",
    "lỗ hổng",
    "vulnerability",
    "scan",
    "pen test",
    "safe",
    "sanitize",
    "escape",
    "csrf",
    "cors",
  ],
  "firecrawl": [
    "crawl",
    "scrape",
    "web",
    "search",
    "content",
    "trích xuất",
    "extract",
    "markdown",
    "url",
    "fetch",
    "data extraction",
    "database",
  ],
  "fiftyone": [
    "dataset",
    "image",
    "computer vision",
    "annotation",
    "cv",
    "object detection",
    "classification",
    "segmentation",
    "visualize",
    "plot",
    "histogram",
    "embedding",
    "相似",
    "duplicate",
  ],
  "sentry": [
    "sentry",
    "error tracking",
    "monitor",
    "alert",
    "crash",
    "exception",
    "log",
    "debug production",
    " incident",
    "oncall",
  ],
  "linear": [
    "linear",
    "task",
    "ticket",
    "issue",
    "project management",
    "backlog",
    "sprint",
    "roadmap",
    "assign",
    "priority",
  ],
  "gitlab": [
    "gitlab",
    "ci/cd",
    "pipeline",
    "merge request",
    "repository",
    "self-hosted",
    "runner",
    "deploy",
  ],
  "serena": [
    "serena",
    "context",
    "memory",
    "session",
    "recall",
    "lưu trạng thái",
    "resume",
  ],
  "greptile": [
    "greptile",
    "codebase chat",
    "ask code",
    "understand",
    "giải thích code",
    "tìm hiểu",
    "navigate",
  ],
  "firebase": [
    "firebase",
    "hosting",
    "firestore",
    "cloud function",
    "mobile",
    "push notification",
    "analytics",
    "crashlytics",
  ],
  "hookify": [
    "hook",
    "rule",
    "prevent",
    "block",
    "guard",
    "ngăn chặn",
    "quy tắc",
    "tự động kiểm tra",
  ],
  "ralph-loop": [
    "loop",
    "recurring",
    "schedule",
    "cron",
    "repeat",
    "lặp lại",
    "định kỳ",
    "tự động chạy",
  ],
  "vibeguide_scan_repo": [
    "quét",
    "scan",
    "repo",
    "structure",
    "cấu trúc",
    "liệt kê file",
    "folder",
    "overview",
    "không biết",
    "codebase",
    "có gì",
    "tổng quan",
    "danh sách file",
    "khám phá",
  ],
  "vibeguide_heuristic_bug": [
    "lỗi",
    "crash",
    "error",
    "fix",
    "sửa",
    "không chạy",
    "không ăn",
    "bị lỗi",
    "fail",
    "proxy",
    "connection",
    "socks",
    "timeout",
    "refuse",
    "không kết nối",
    "mất kết nối",
  ],
  "vibeguide_trace_journey": [
    "luồng",
    "journey",
    "flow",
    "entry point",
    "user click",
    "người dùng bấm",
    "tương tác",
    "hành trình",
    "trace",
    "theo dõi",
  ],
  "vibeguide_impact": [
    "ảnh hưởng",
    "impact",
    "risk",
    "thay đổi",
    "đụng chạm",
    "affected files",
    "liên quan",
    "đụng",
    "scope",
    "phạm vi",
  ],
  "vibeguide_test_plan": [
    "test",
    "kiểm thử",
    "plan",
    "test case",
    "qa",
    "kiểm tra",
    "hướng dẫn test",
    "founder test",
    "kịch bản test",
    "fix",
  ],
  "vibeguide_snapshot": [
    "snapshot",
    "backup",
    "rollback",
    "phục hồi",
    "chụp",
    "lưu trạng thái",
    "trước khi sửa",
    "điểm phục hồi",
  ],
  "vibeguide_deploy_check": [
    "deploy",
    "production",
    "release",
    "đẩy lên",
    "kiểm tra trước deploy",
    "pre-deploy",
    "production ready",
    "orphan",
    "file chết",
    "không dùng",
    "uncommitted",
    "bug pattern",
  ],
  "vibeguide_suggest_fix": [
    "sửa",
    "fix",
    "code suggestion",
    "gợi ý sửa",
    "autofix",
    "correct",
    "patch",
    "refactor suggestion",
  ],
  "vibeguide_changelog": [
    "changelog",
    "history",
    "commit log",
    "thay đổi",
    "release note",
    "version",
    "update log",
    "lịch sử",
    "commit",
  ],
  "vibeguide_dependency_graph": [
    "dependency",
    "graph",
    "mermaid",
    "diagram",
    "sơ đồ",
    "liên kết",
    "import",
    "module graph",
    "visualize dependency",
  ],
  "vibeguide_diff_summary": [
    "diff",
    "so sánh",
    "thay đổi",
    "tóm tắt thay đổi",
    "code review diff",
    "what changed",
  ],
  "vibeguide_what_changed": [
    "what changed",
    "recent",
    "commit gần đây",
    "vừa sửa",
    "mới thay đổi",
    "recent commits",
    "thay đổi gần đây",
  ],
  "vibeguide_regression": [
    "regression",
    "lùi",
    "hỏng lại",
    "test lại",
    "kiểm tra hồi quy",
    "affected flows",
    "kiểm tra lại",
  ],
  "vibeguide_get_file": [
    "đọc file",
    "xem code",
    "file content",
    "nội dung file",
    "mở file",
    "read file",
  ],
  "vibeguide_get_deps": [
    "dependency graph",
    "deps",
    "import",
    "module",
    "phụ thuộc",
    "liên kết file",
  ],
  "vibeguide_type_check": [
    "type",
    "typescript",
    "compile",
    "type error",
    "kiểu",
    "lỗi kiểu",
    "ts",
    "tsc",
  ],
  "vibeguide_test_coverage": [
    "coverage",
    "test coverage",
    "độ phủ",
    "weak test",
    "coverage report",
    "phủ test",
  ],
  "vibeguide_circular_deps": [
    "circular",
    "vòng lặp import",
    "cycle",
    "circular dependency",
    "import vòng",
  ],
  "vibeguide_dead_code": [
    "dead code",
    "unused",
    "orphan",
    "file chết",
    "không dùng",
    "code thừa",
  ],
  "vibeguide_complexity": [
    "complexity",
    "phức tạp",
    "cyclomatic",
    "refactor complex",
    "loc",
    "quá dài",
  ],
  "vibeguide_a11y_check": [
    "a11y",
    "accessibility",
    "wcag",
    "alt",
    "aria",
    "screen reader",
    "khả năng tiếp cận",
  ],
  "vibeguide_secret_scan": [
    "secret",
    "api key",
    "credential",
    "leak",
    "password",
    "token",
    "credential leak",
    "lộ key",
  ],
  "vibeguide_i18n_gap": [
    "i18n",
    "translation",
    "locale",
    "missing key",
    "đa ngôn ngữ",
    "dịch",
    "thiếu bản dịch",
  ],
  "vibeguide_doc_gap": [
    "documentation",
    "jsdoc",
    "readme",
    "thiếu tài liệu",
    "tài liệu",
    "doc",
  ],
  "vibeguide_perf_budget": [
    "bundle size",
    "performance budget",
    "tối ưu kích thước",
    "slow bundle",
    "bundle quá lớn",
  ],
  "vibeguide_monorepo_route": [
    "monorepo",
    "workspace",
    "package",
    "nx",
    "turbo",
    "pnpm workspace",
  ],
  "vibeguide_review_pr": [
    "review pr",
    "merge check",
    "pre-merge",
    "duyệt pull request",
    "review code",
    "kiểm tra trước merge",
  ],
  "vibeguide_founder_brief": [
    "founder report",
    "báo cáo tuần",
    "weekly summary",
    "tóm tắt cho founder",
    "báo cáo nhanh",
  ],
  "vibeguide_meeting_notes": [
    "meeting notes",
    "biên bản họp",
    "standup",
    "meeting summary",
    "ghi chú họp",
  ],
};
